version: '3.8'

services:
  frontend:
    build: .
    container_name: mercado-front
    restart: always
    environment:
      - UrlWebAPI=http://host.docker.internal:3000     
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "8080"

  proxy:
    image: nginx:alpine
    container_name: mercado-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend